### ISSUE TITLE
我的lora   sx127X 通讯距离很差，在软件上应该怎么配置，才可以提高lora 的通讯距离

### ISSUE THREAD

**Issue by huangdiajd** [dernasherbrezon/sx127x#10]
您好，目前我使用 receive_lora 和transmit_lora 例程进行通讯，发现通讯距离只有几米，我应该怎么解决这个问题？

**Comment by dernasherbrezon** [comment]
你好，

您需要使用此函数增加接收器的增益：sx127x_rx_set_lna_gain

对于发射机增加功率：
sx127x_tx_set_pa_config

这是一般性建议，但如果您想真正提高覆盖范围，则需要调整 LoRa 特定参数，例如带宽、编码率和扩频因子。

**Comment by huangdiajd** [comment]
![image](https://github.com/dernasherbrezon/sx127x/assets/108785632/0483d487-3232-4ea8-8970-2c45cd138abe)
nin您好，我现在遇到一个问题，就是我这个lora发送的回调函数，放在while(1)外面只执行一次就不执行了，然后放在while(1)里面是可以正常执行起来的，但是我现在在这个回调函数里面使用文件系统总是会把文件系统给删除掉了，我想问一下，我这个回调函数，放在while(1)里面，有没有什么大的问题？

**Comment by dernasherbrezon** [comment]
如果没有 tx_hi_callback 源，很难判断。 然而 sx127x 设计为使用中断。 所以不需要使用 while(1) 或等待。 您需要配置一次回调并在提供的函数中处理中断。
