### ISSUE TITLE
FIFO Problem

### ISSUE THREAD

**Issue by Pascal66** [dernasherbrezon/sx127x#11]
My received frames are always truncated of the first byte.
This is because you remove the first byte, considering it's only the packet_length stored on it in the case of VARIABLE.

In my implementation, my first byte contain not only the packet_lenght and other flags on it.

**Comment by dernasherbrezon** [comment]
According to the specification length must be 1 byte:

<img width="767" alt="Screenshot 2024-03-25 at 18 48 04" src="https://github.com/dernasherbrezon/sx127x/assets/1614424/a3c5bfd2-2a15-4253-9383-c0f526c8f8e2">

**Comment by dernasherbrezon** [comment]
Yes, but this will make API inconsistent:

- LoRa and "fixed packet" mode don't expect length to be the first byte
- Make inconsistent with TX. The ```uint8_t *data``` that was set in ```sx127x_fsk_ook_tx_set_for_transmission``` should be received as-is in the RX callback.

**Comment by dernasherbrezon** [comment]
I also noticed when I used SPI speed ~8Mhz, data gets corrupted. I guess my ESP32 is not fast enough or crystal is not stable enough to generate good 8Mhz SPI signal. Some bit might flip when you send long sequence of "0" or "1". It can be solved by sending scrambled data.

**Comment by dernasherbrezon** [comment]
> The SX1276 with SPI & DMA is at 10MHz and mode 0

Then maybe this is causing such issue. I don't have oscilloscope with ~16Mhz sampling rate to check that. Even if SX1276 rated at 10Mhz, it is not clear how they got this number. Maybe they used external TXCO with ~1ppm (connected to XTA pin). I think it depends on how the chip is connected to the rest of the board. Internal sx127x crystal is 20ppm.

<img width="517" alt="Screenshot 2024-03-29 at 14 56 42" src="https://github.com/dernasherbrezon/sx127x/assets/1614424/2bbc2dea-75d1-4912-8710-3ed3b5607d28">
