### ISSUE TITLE
Compiling on ESP32C6 board

### ISSUE THREAD

**Issue by VitorCMatias** [dernasherbrezon/sx127x#12]
Hello, 

I am using the example present in the repo to make my project, when I compile to the ESP32 board it works. However, when I try on my C6 I receive the following error:

![image](https://github.com/dernasherbrezon/sx127x/assets/43122957/9ecab6f9-e6e7-4658-84e1-d7315d028ab1)

I am using the espidf environment in vscode.

**Comment by VitorCMatias** [comment]
If I follow the compiler tip the build works, but I don't know if it will affect the component behaviour. I am a beginner in the espidf environment

**Comment by dernasherbrezon** [comment]
Looks like ```HSPI_HOST``` was deprecated at some point:
https://github.com/espressif/esp-idf/blob/master/components/hal/include/hal/spi_types.h#L81

It is safe to use ```SPI2_HOST```.
