### ISSUE TITLE
Running on ESP32C6

### ISSUE THREAD

**Issue by VitorCMatias** [dernasherbrezon/sx127x#13]
Hello again,
I'm attempting to execute code on my ESP32, but I encounter an error. It appears after flashing when I open the serial terminal.
![image](https://github.com/dernasherbrezon/sx127x/assets/43122957/3572e378-3f99-4912-adc9-3320df004407)

**Comment by dernasherbrezon** [comment]
Hi,

It looks like the chip you have is not sx127x. Thus error "SX127X_ERR_INVALID_VERSION".

**Comment by VitorCMatias** [comment]
The device is an SX1278. It worked on my Arduino nano and other ESP32 board with Arduino framework. I verify the pinout but the error persists
![Imagem do WhatsApp de 2024-04-15 à(s) 17 49 31_84bc82d1](https://github.com/dernasherbrezon/sx127x/assets/43122957/51073a10-4aa5-4a48-a854-bf2fdf6904cc)

**Comment by dernasherbrezon** [comment]
Interesting. The issue might be somewhere in the SPI configuration then. I.e. you're getting some data, but this data either is corrupted or maybe coming from the different chip. I recall you had issue with compilation #12. Is it possible that the chip is actually connected to SPI1_HOST and not SPI2_HOST?

**Comment by VitorCMatias** [comment]
I tried but got the same error. When you developed the example code which ESP32 you had in mind? I am using a ESP32-C6-DevKitM-1.

**Comment by dernasherbrezon** [comment]
it was ESP32-PICO-D4 from TTGO Lora32 and Heltec Lora v2.
