### ISSUE TITLE
Not receiving any signal (868MHz FSK)

### ISSUE THREAD

**Issue by pksimeonov** [dernasherbrezon/sx127x#14]
I have a small ESP-IDF Project for a Lilygo T3 S3 board (SX1276). I'm trying to receive data from Ecowitt WH51 sensors (868MHz FSK, various sources claim 868.35MHz should be used for best results). I started with the "receive_fsk" example in this repo and I replaced `HSPI_HOST` with `SPI2_HOST` (per https://github.com/dernasherbrezon/sx127x/issues/12#issuecomment-2030311596). I set the GPIO pins like they are in Lilygo's LoRa example projects for this board model, the project builds and runs. The 868MHz antenna (came with the board) is installed and my WH51 is right next to it.

I have tried all sorts of setting combinations, but I don't seem to get any signal at all. The sensor regularly blinks signifying that a reading was sent, but nothing seems to be received by the board. I have two of the Lilygo boards and they talk fine to each other when I tested them with Meshtastic so I'm fairly confident it's not a hardware issue. Any ideas on what settings to try / tips on how to troubleshoot further?

**Comment by dernasherbrezon** [comment]
Hi,

I suggest the following:

1. Try ```receive_fsk``` and ```transmit_fsk``` to check if wiring is correct and messages are coming between devices
2. Check the frame structure sent by Ecowitt WH51 sensors. sx127x FSK mode expect very specific frames, that might not be compatible with Ecowitt WH51.
3. If none helped, try sniffing radio traffic using rtl-sdr and visualise the message with tools like [inspectrum](https://github.com/miek/inspectrum)
