### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by ahsimb** [dernasherbrezon/sx127x#15]
I've got an SX1272 module, which I thought would be supported by this library. However, the version (or Semtech ID) I am getting at the address 0x42 is 34 as per the product [datasheet](https://www.rfsolutions.co.uk/downloads/1462271988SX1272_SEMTECH.pdf). The library expects the value 18 and refuses to work after seeing a different number.

Is this a new, incompatible version?

**Comment by dernasherbrezon** [comment]
Yes, look like incompatible. I will have a look into the differences to sx1276/77/78/79.

**Comment by ahsimb** [comment]
Thanks a lot.

**Comment by dernasherbrezon** [comment]
Where did you get this chip? I can't find any dev board to buy and test.

**Comment by ahsimb** [comment]
[Here](https://www.rfsolutions.co.uk//radio-modules-c10/lora-transceiver-module-dip-package-p644/s647) is what I bought.

**Comment by ahsimb** [comment]
They claim their module can transmit over up to 16 km in theory and up to 12 km according to their tests. What makes it cover a longer distance compared to other modules with a similar chip I do not understand. I wanted to give it a try.  Disclaimer: I am not particularly knowledgeable in this area. The project is more like a hobby for me.

**Comment by dernasherbrezon** [comment]
No :)

Semtech is the manufacturer of these chips. If they believe sensitivity is better on sx1276 series, then this is most likely it. They know internals of the chip better than anyone else. Think of it as a theoretical sensitivity. In practice, these chips need to be soldered and integrated somewhere. And this is where numbers can be different. Maybe RFSolutions did a good job designing and testing the board. And it might be better than someone' else result with sx1276. But it is also possible that someone' else did a good job integrating sx1276.

But all of this is irrelevant if the final board connected to unbalanced antenna or working in a very noisy environment.

**Comment by ahsimb** [comment]
They probably did a good job if the results of their tests were to be trusted - 12+ km with a line of sight and 3 km with no line of sight. This is considerably better than what I have seen elsewhere (again, I am not a specialist). I don't know why they use sx1272 instead of the more advanced sx1276. Probably because they have a big stock of sx1272 which they want to get rid of.

**Comment by dernasherbrezon** [comment]
Yes, most likely. sx1272 is hard to find. 

FYI Stock LoRa chips can receive data from satellites which is slightly more than 12+ km.

**Comment by ahsimb** [comment]
Very interesting. Thanks for sharing. I guess it's not exactly my case, as the transmitter on a satellite takes a bit more power than what AA batteries can give.

**Comment by dernasherbrezon** [comment]
I compared registers between sx1272/73 and sx1276/77/78/79 and found lots of differences. So this project is not suitable for sx1272/73 chips. I probably create a separate project to support that. In the meantime, better use some other projects.
