### ISSUE TITLE
FSK beacon not working properly

### ISSUE THREAD

**Issue by mostorer** [dernasherbrezon/sx127x#17]
I have found an issue when using beacon mode in FSK on an esp32c3.

Replicate it is quite simple ... if you use an interval of 17ms or more, all is working as expected but, if you set an interval of 16ms or less, only one packet is transmitted.

Replicating the issue is quite easy:

Cloned you example, then changed the bitrate to 38.400:
`ESP_ERROR_CHECK(sx127x_fsk_ook_set_bitrate(38400.0, &device));`

and the start_beacon with interval=16ms to:
`ESP_ERROR_CHECK(sx127x_fsk_ook_tx_start_beacon(payload, sizeof(payload), 16, &device));`

The packet within the example is sent in less than 4ms as it is of 6 bytes + 2 sync +4 preamble +2 crc = 14bytes * 9bits:

(14 * 9)/38400 = 0,00328 S

so I would expect to have no trouble with an interval > 4ms

**Comment by mostorer** [comment]
Looking at your code, it seems to me that the issue is within the first "if" block to determine coefficients and resolution, starting at line 984:

`  if (interval_ms <= 255 * p1) {
    timer1_resolution = p1;
    timer1_coefficient = (uint8_t) (interval_ms / p1);`

**Comment by dernasherbrezon** [comment]
Here is how 10ms beacon looks like on the spectrogram:

<img width="606" alt="Screenshot 2024-11-19 at 20 06 44" src="https://github.com/user-attachments/assets/c203eae1-ea5c-48c5-8bfb-a64504f10c7f">

**Comment by mostorer** [comment]
> Do you really send beacons every 16ms? Or just generally curious?

Yes, I use beacons to send bursts of packets to devices mostly in standby. I could also call the `sx127x_fsk_ook_tx_set_for_transmission` function multiple times but, why doing that when I can use beacons ?
