### ISSUE TITLE
[REQUEST] Weak functions for SPI hal implementation

### ISSUE THREAD

**Issue by liliumjsn** [dernasherbrezon/sx127x#3]
Hello,

Is it possible to make the sx127x_esp_spi.c functions __weak so we can override them with our own SPI implementation?

Thank you,
Dimitris

**Comment by dernasherbrezon** [comment]
Hi,

sx127x.c doesn't depend on any SPI implementations. You can implement functions defined at https://github.com/dernasherbrezon/sx127x/blob/main/include/sx127x_spi.h and link them accordingly to the sx127x.o.

Here is how you can link different SPI implementations:

```
set(srcs
    "${CMAKE_CURRENT_SOURCE_DIR}/src/sx127x.c"
)
if (CUSTOM_ARCHITECTURE)
list(APPEND srcs "${CMAKE_CURRENT_SOURCE_DIR}/src/sx127x_mycustom_spi.c")
    add_library(sx127x STATIC ${srcs})
endif()
```

**Comment by liliumjsn** [comment]
The point was to use this repo as a submodule as it is so we can follow its updates.
If we edit your CMakeLists.txt that's not the case. That's why I suggested the __weak functions.

**Comment by dernasherbrezon** [comment]
I see. I think in that case you can completely ignore cmakelists.txt and reference source and includes from the outside.

for example in the top level cmakelists:


list(APPEND srcs "${CMAKE_CURRENT_SOURCE_DIR}/sx127x/src/sx127x.c")

and also your own implementation of spi:

list(APPEND srcs "${CMAKE_CURRENT_SOURCE_DIR}/sx127x_mycustom_spi.c")

will it work for you?
