### ISSUE TITLE
[request] configure chip select pin on Linux

### ISSUE THREAD

**Issue by biemster** [dernasherbrezon/sx127x#5]
I have multiple devices on my SPI bus (on QCA9533), and need to assign a CS line to each. In the rpi example the code mentions spidev0.0 has this standard on GPIO8, where should I define the pin in my case?
Or should I pull this pin up before running this code?

**Comment by dernasherbrezon** [comment]
It's on raspberry pi's pinout diagram:

<img width="555" alt="Screenshot 2023-10-11 at 13 56 07" src="https://github.com/dernasherbrezon/sx127x/assets/1614424/fabda26f-7ab9-4890-b855-cba96619bad3">

**Comment by dernasherbrezon** [comment]
Ah, I see. No sx127x doesn't deal with pins. It accepts only correctly configured spi device. Actually esp32 and linux correctly pull down CS line before transfer command and data. So you don't need to do anything specific.

**Comment by biemster** [comment]
Ah, did not know that! Thanks for that info!
So I guess I have to set which gpio I want to use as CS line in the DTS?
Anyway thanks for clearing this up for me, I'll figure that out myself. Great project btw!
