### ISSUE TITLE
Any plan to make an FSK send receive example ?

### ISSUE THREAD

**Issue by Pascal66** [dernasherbrezon/sx127x#7]
Wish to have an example with send receive to migrate my simple code from radiolib to yours.

**Comment by dernasherbrezon** [comment]
It's there:
Receive: https://github.com/dernasherbrezon/sx127x/tree/main/examples/receive_fsk
Transmit: https://github.com/dernasherbrezon/sx127x/tree/main/examples/transmit_fsk
