### ISSUE TITLE
我的lora 设备分时复用 接收和发送模式，不能实现。

### ISSUE THREAD

**Issue by huangdiajd** [dernasherbrezon/sx127x#8]
我现在的问题就是 设备2给设备一发送数据，设备1接收到设备2发送的数据就切换到发送模式（目前设备1切换到发送模式下，只能发送一会数据就不发送了）

请问下有没有相关方法可以解决这个问题？

**Comment by dernasherbrezon** [comment]
您能否确保 rx 和 tx 的寄存器和回调在启动时初始化。 那么在操作期间在接收和发送之间切换应该不会花费太多时间。 如果这没有帮助，请尝试使用 RTL-SDR 监控无线电，并检查设备 2 上的发射器在一段时间后是否确实在发射。
